name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC
      run: | 
        sudo apt-get install -y build-essential
        sudo apt-get install -y libcunit1 libcunit1-dev

    - name: Run tests
      run: make run_tests  # Ensure you have a 'test' target in your Makefile

    - name: Run distcheck
      run: make distcheck  # Ensure this target is defined in your Makefile
