name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y build-essential

    - name: Build the application
      run: make

    - name: Run tests
      run: make test  # Ensure you have a 'test' target in your Makefile

    - name: Run distcheck
      run: make distcheck  # Ensure this target is defined in your Makefile
