name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC
      run: | 
        sudo apt-get install -y build-essential
        sudo apt-get install -y libcunit1 libcunit1-dev

    - name: Build tests
      run: make build_tests

    - name: Run tests
      run: |
        ./tests | tee test_results.log  # Redirect output to log file and display on console
        echo "Test Results:"
        cat test_results.log  # Display the log file

    - name: Run distcheck
      run: make distcheck  # Ensure this target is defined in your Makefile
