name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GCC
      run: | 
        sudo apt-get install -y build-essential
        sudo apt-get install -y libcunit1 libcunit1-dev

    - name: Build tests
      run: make build_tests

    - name: Run tests
      run: make run_tests
